// Generated by the iod symbol generator.
#include <iod/symbol/symbol.hh>
#ifndef IOD_SYMBOL_address
#define IOD_SYMBOL_address
    IOD_SYMBOL(address)
#endif

#ifndef IOD_SYMBOL_after_destroy
#define IOD_SYMBOL_after_destroy
    IOD_SYMBOL(after_destroy)
#endif

#ifndef IOD_SYMBOL_after_insert
#define IOD_SYMBOL_after_insert
    IOD_SYMBOL(after_insert)
#endif

#ifndef IOD_SYMBOL_age
#define IOD_SYMBOL_age
    IOD_SYMBOL(age)
#endif

#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    IOD_SYMBOL(auto_increment)
#endif

#ifndef IOD_SYMBOL_before_insert
#define IOD_SYMBOL_before_insert
    IOD_SYMBOL(before_insert)
#endif

#ifndef IOD_SYMBOL_charset
#define IOD_SYMBOL_charset
    IOD_SYMBOL(charset)
#endif

#ifndef IOD_SYMBOL_city
#define IOD_SYMBOL_city
    IOD_SYMBOL(city)
#endif

#ifndef IOD_SYMBOL_database
#define IOD_SYMBOL_database
    IOD_SYMBOL(database)
#endif

#ifndef IOD_SYMBOL_get
#define IOD_SYMBOL_get
    IOD_SYMBOL(get)
#endif

#ifndef IOD_SYMBOL_get_parameters
#define IOD_SYMBOL_get_parameters
    IOD_SYMBOL(get_parameters)
#endif

#ifndef IOD_SYMBOL_host
#define IOD_SYMBOL_host
    IOD_SYMBOL(host)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    IOD_SYMBOL(id)
#endif

#ifndef IOD_SYMBOL_id2
#define IOD_SYMBOL_id2
    IOD_SYMBOL(id2)
#endif

#ifndef IOD_SYMBOL_jsonencoded
#define IOD_SYMBOL_jsonencoded
    IOD_SYMBOL(jsonencoded)
#endif

#ifndef IOD_SYMBOL_login
#define IOD_SYMBOL_login
    IOD_SYMBOL(login)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    IOD_SYMBOL(name)
#endif

#ifndef IOD_SYMBOL_non_blocking
#define IOD_SYMBOL_non_blocking
    IOD_SYMBOL(non_blocking)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    IOD_SYMBOL(password)
#endif

#ifndef IOD_SYMBOL_path
#define IOD_SYMBOL_path
    IOD_SYMBOL(path)
#endif

#ifndef IOD_SYMBOL_port
#define IOD_SYMBOL_port
    IOD_SYMBOL(port)
#endif

#ifndef IOD_SYMBOL_post
#define IOD_SYMBOL_post
    IOD_SYMBOL(post)
#endif

#ifndef IOD_SYMBOL_post_parameters
#define IOD_SYMBOL_post_parameters
    IOD_SYMBOL(post_parameters)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    IOD_SYMBOL(primary_key)
#endif

#ifndef IOD_SYMBOL_read_only
#define IOD_SYMBOL_read_only
    IOD_SYMBOL(read_only)
#endif

#ifndef IOD_SYMBOL_synchronous
#define IOD_SYMBOL_synchronous
    IOD_SYMBOL(synchronous)
#endif

#ifndef IOD_SYMBOL_test1
#define IOD_SYMBOL_test1
    IOD_SYMBOL(test1)
#endif

#ifndef IOD_SYMBOL_test2
#define IOD_SYMBOL_test2
    IOD_SYMBOL(test2)
#endif

#ifndef IOD_SYMBOL_user
#define IOD_SYMBOL_user
    IOD_SYMBOL(user)
#endif

#ifndef IOD_SYMBOL_user_id
#define IOD_SYMBOL_user_id
    IOD_SYMBOL(user_id)
#endif

