// Generated by the lithium symbol generator.
#include <li/symbol/symbol.hh>
#ifndef LI_SYMBOL_test1
#define LI_SYMBOL_test1
    LI_SYMBOL(test1)
#endif

#ifndef LI_SYMBOL_test2
#define LI_SYMBOL_test2
    LI_SYMBOL(test2)
#endif

#ifndef LI_SYMBOL_test3
#define LI_SYMBOL_test3
    LI_SYMBOL(test3)
#endif

#ifndef LI_SYMBOL_test4
#define LI_SYMBOL_test4
    LI_SYMBOL(test4)
#endif

#ifndef LI_SYMBOL_test5
#define LI_SYMBOL_test5
    LI_SYMBOL(test5)
#endif

