// Generated by the iod symbol generator.
#include <iod/symbol/symbol.hh>
#ifndef IOD_SYMBOL_append
#define IOD_SYMBOL_append
    IOD_SYMBOL(append)
#endif

#ifndef IOD_SYMBOL_json_key
#define IOD_SYMBOL_json_key
    IOD_SYMBOL(json_key)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    IOD_SYMBOL(name)
#endif

#ifndef IOD_SYMBOL_type
#define IOD_SYMBOL_type
    IOD_SYMBOL(type)
#endif

