// Generated by the iod symbol generator.
#include <iod/symbol/symbol.hh>
#ifndef IOD_SYMBOL_age
#define IOD_SYMBOL_age
    IOD_SYMBOL(age)
#endif

#ifndef IOD_SYMBOL_charset
#define IOD_SYMBOL_charset
    IOD_SYMBOL(charset)
#endif

#ifndef IOD_SYMBOL_database
#define IOD_SYMBOL_database
    IOD_SYMBOL(database)
#endif

#ifndef IOD_SYMBOL_host
#define IOD_SYMBOL_host
    IOD_SYMBOL(host)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    IOD_SYMBOL(id)
#endif

#ifndef IOD_SYMBOL_name
#define IOD_SYMBOL_name
    IOD_SYMBOL(name)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    IOD_SYMBOL(password)
#endif

#ifndef IOD_SYMBOL_user
#define IOD_SYMBOL_user
    IOD_SYMBOL(user)
#endif

