// Generated by the iod symbol generator.
#include <iod/symbol/symbol.hh>
#ifndef IOD_SYMBOL_ATTR
#define IOD_SYMBOL_ATTR
    IOD_SYMBOL(ATTR)
#endif

#ifndef IOD_SYMBOL_after_destroy
#define IOD_SYMBOL_after_destroy
    IOD_SYMBOL(after_destroy)
#endif

#ifndef IOD_SYMBOL_after_insert
#define IOD_SYMBOL_after_insert
    IOD_SYMBOL(after_insert)
#endif

#ifndef IOD_SYMBOL_after_update
#define IOD_SYMBOL_after_update
    IOD_SYMBOL(after_update)
#endif

#ifndef IOD_SYMBOL_auto_increment
#define IOD_SYMBOL_auto_increment
    IOD_SYMBOL(auto_increment)
#endif

#ifndef IOD_SYMBOL_before_create
#define IOD_SYMBOL_before_create
    IOD_SYMBOL(before_create)
#endif

#ifndef IOD_SYMBOL_before_destroy
#define IOD_SYMBOL_before_destroy
    IOD_SYMBOL(before_destroy)
#endif

#ifndef IOD_SYMBOL_before_insert
#define IOD_SYMBOL_before_insert
    IOD_SYMBOL(before_insert)
#endif

#ifndef IOD_SYMBOL_before_update
#define IOD_SYMBOL_before_update
    IOD_SYMBOL(before_update)
#endif

#ifndef IOD_SYMBOL_blocking
#define IOD_SYMBOL_blocking
    IOD_SYMBOL(blocking)
#endif

#ifndef IOD_SYMBOL_https_cert
#define IOD_SYMBOL_https_cert
    IOD_SYMBOL(https_cert)
#endif

#ifndef IOD_SYMBOL_https_key
#define IOD_SYMBOL_https_key
    IOD_SYMBOL(https_key)
#endif

#ifndef IOD_SYMBOL_id
#define IOD_SYMBOL_id
    IOD_SYMBOL(id)
#endif

#ifndef IOD_SYMBOL_linux_epoll
#define IOD_SYMBOL_linux_epoll
    IOD_SYMBOL(linux_epoll)
#endif

#ifndef IOD_SYMBOL_non_blocking
#define IOD_SYMBOL_non_blocking
    IOD_SYMBOL(non_blocking)
#endif

#ifndef IOD_SYMBOL_nthreads
#define IOD_SYMBOL_nthreads
    IOD_SYMBOL(nthreads)
#endif

#ifndef IOD_SYMBOL_on_create_success
#define IOD_SYMBOL_on_create_success
    IOD_SYMBOL(on_create_success)
#endif

#ifndef IOD_SYMBOL_on_destroy_success
#define IOD_SYMBOL_on_destroy_success
    IOD_SYMBOL(on_destroy_success)
#endif

#ifndef IOD_SYMBOL_on_update_success
#define IOD_SYMBOL_on_update_success
    IOD_SYMBOL(on_update_success)
#endif

#ifndef IOD_SYMBOL_one_thread_per_connection
#define IOD_SYMBOL_one_thread_per_connection
    IOD_SYMBOL(one_thread_per_connection)
#endif

#ifndef IOD_SYMBOL_primary_key
#define IOD_SYMBOL_primary_key
    IOD_SYMBOL(primary_key)
#endif

#ifndef IOD_SYMBOL_read_access
#define IOD_SYMBOL_read_access
    IOD_SYMBOL(read_access)
#endif

#ifndef IOD_SYMBOL_read_only
#define IOD_SYMBOL_read_only
    IOD_SYMBOL(read_only)
#endif

#ifndef IOD_SYMBOL_select
#define IOD_SYMBOL_select
    IOD_SYMBOL(select)
#endif

#ifndef IOD_SYMBOL_validate
#define IOD_SYMBOL_validate
    IOD_SYMBOL(validate)
#endif

#ifndef IOD_SYMBOL_write_access
#define IOD_SYMBOL_write_access
    IOD_SYMBOL(write_access)
#endif

