// Generated by the iod symbol generator.
#include <li/symbol/symbol.hh>
#ifndef LI_SYMBOL_body
#define LI_SYMBOL_body
    LI_SYMBOL(body)
#endif

#ifndef LI_SYMBOL_get_parameters
#define LI_SYMBOL_get_parameters
    LI_SYMBOL(get_parameters)
#endif

#ifndef LI_SYMBOL_jsonencoded
#define LI_SYMBOL_jsonencoded
    LI_SYMBOL(jsonencoded)
#endif

#ifndef LI_SYMBOL_method
#define LI_SYMBOL_method
    LI_SYMBOL(method)
#endif

#ifndef LI_SYMBOL_post_parameters
#define LI_SYMBOL_post_parameters
    LI_SYMBOL(post_parameters)
#endif

#ifndef LI_SYMBOL_status
#define LI_SYMBOL_status
    LI_SYMBOL(status)
#endif

