// Generated by the lithium symbol generator.
#include <lithium_symbol.hh>
#ifndef LI_SYMBOL_adhocFilters
#define LI_SYMBOL_adhocFilters
    LI_SYMBOL(adhocFilters)
#endif

#ifndef LI_SYMBOL_age
#define LI_SYMBOL_age
    LI_SYMBOL(age)
#endif

#ifndef LI_SYMBOL_entry
#define LI_SYMBOL_entry
    LI_SYMBOL(entry)
#endif

#ifndef LI_SYMBOL_format
#define LI_SYMBOL_format
    LI_SYMBOL(format)
#endif

#ifndef LI_SYMBOL_from
#define LI_SYMBOL_from
    LI_SYMBOL(from)
#endif

#ifndef LI_SYMBOL_id
#define LI_SYMBOL_id
    LI_SYMBOL(id)
#endif

#ifndef LI_SYMBOL_interval
#define LI_SYMBOL_interval
    LI_SYMBOL(interval)
#endif

#ifndef LI_SYMBOL_intervalMs
#define LI_SYMBOL_intervalMs
    LI_SYMBOL(intervalMs)
#endif

#ifndef LI_SYMBOL_maxDataPoints
#define LI_SYMBOL_maxDataPoints
    LI_SYMBOL(maxDataPoints)
#endif

#ifndef LI_SYMBOL_message
#define LI_SYMBOL_message
    LI_SYMBOL(message)
#endif

#ifndef LI_SYMBOL_name
#define LI_SYMBOL_name
    LI_SYMBOL(name)
#endif

#ifndef LI_SYMBOL_panelId
#define LI_SYMBOL_panelId
    LI_SYMBOL(panelId)
#endif

#ifndef LI_SYMBOL_range
#define LI_SYMBOL_range
    LI_SYMBOL(range)
#endif

#ifndef LI_SYMBOL_rangeRaw
#define LI_SYMBOL_rangeRaw
    LI_SYMBOL(rangeRaw)
#endif

#ifndef LI_SYMBOL_raw
#define LI_SYMBOL_raw
    LI_SYMBOL(raw)
#endif

#ifndef LI_SYMBOL_refId
#define LI_SYMBOL_refId
    LI_SYMBOL(refId)
#endif

#ifndef LI_SYMBOL_target
#define LI_SYMBOL_target
    LI_SYMBOL(target)
#endif

#ifndef LI_SYMBOL_targets
#define LI_SYMBOL_targets
    LI_SYMBOL(targets)
#endif

#ifndef LI_SYMBOL_test1
#define LI_SYMBOL_test1
    LI_SYMBOL(test1)
#endif

#ifndef LI_SYMBOL_test2
#define LI_SYMBOL_test2
    LI_SYMBOL(test2)
#endif

#ifndef LI_SYMBOL_to
#define LI_SYMBOL_to
    LI_SYMBOL(to)
#endif

#ifndef LI_SYMBOL_type
#define LI_SYMBOL_type
    LI_SYMBOL(type)
#endif

