// Generated by the iod symbol generator.
#include <iod/symbol/symbol.hh>
#ifndef IOD_SYMBOL_charset
#define IOD_SYMBOL_charset
    IOD_SYMBOL(charset)
#endif

#ifndef IOD_SYMBOL_database
#define IOD_SYMBOL_database
    IOD_SYMBOL(database)
#endif

#ifndef IOD_SYMBOL_host
#define IOD_SYMBOL_host
    IOD_SYMBOL(host)
#endif

#ifndef IOD_SYMBOL_password
#define IOD_SYMBOL_password
    IOD_SYMBOL(password)
#endif

#ifndef IOD_SYMBOL_port
#define IOD_SYMBOL_port
    IOD_SYMBOL(port)
#endif

#ifndef IOD_SYMBOL_synchronous
#define IOD_SYMBOL_synchronous
    IOD_SYMBOL(synchronous)
#endif

#ifndef IOD_SYMBOL_user
#define IOD_SYMBOL_user
    IOD_SYMBOL(user)
#endif

