// Generated by the lithium symbol generator.
#include <lithium_symbol.hh>
#ifndef LI_SYMBOL_after_insert
#define LI_SYMBOL_after_insert
    LI_SYMBOL(after_insert)
#endif

#ifndef LI_SYMBOL_after_remove
#define LI_SYMBOL_after_remove
    LI_SYMBOL(after_remove)
#endif

#ifndef LI_SYMBOL_age
#define LI_SYMBOL_age
    LI_SYMBOL(age)
#endif

#ifndef LI_SYMBOL_auto_increment
#define LI_SYMBOL_auto_increment
    LI_SYMBOL(auto_increment)
#endif

#ifndef LI_SYMBOL_before_insert
#define LI_SYMBOL_before_insert
    LI_SYMBOL(before_insert)
#endif

#ifndef LI_SYMBOL_charset
#define LI_SYMBOL_charset
    LI_SYMBOL(charset)
#endif

#ifndef LI_SYMBOL_database
#define LI_SYMBOL_database
    LI_SYMBOL(database)
#endif

#ifndef LI_SYMBOL_disable_check_certificate
#define LI_SYMBOL_disable_check_certificate
    LI_SYMBOL(disable_check_certificate)
#endif

#ifndef LI_SYMBOL_email
#define LI_SYMBOL_email
    LI_SYMBOL(email)
#endif

#ifndef LI_SYMBOL_fetch_headers
#define LI_SYMBOL_fetch_headers
    LI_SYMBOL(fetch_headers)
#endif

#ifndef LI_SYMBOL_get_parameters
#define LI_SYMBOL_get_parameters
    LI_SYMBOL(get_parameters)
#endif

#ifndef LI_SYMBOL_hash_password
#define LI_SYMBOL_hash_password
    LI_SYMBOL(hash_password)
#endif

#ifndef LI_SYMBOL_host
#define LI_SYMBOL_host
    LI_SYMBOL(host)
#endif

#ifndef LI_SYMBOL_id
#define LI_SYMBOL_id
    LI_SYMBOL(id)
#endif

#ifndef LI_SYMBOL_info
#define LI_SYMBOL_info
    LI_SYMBOL(info)
#endif

#ifndef LI_SYMBOL_json_encoded
#define LI_SYMBOL_json_encoded
    LI_SYMBOL(json_encoded)
#endif

#ifndef LI_SYMBOL_login
#define LI_SYMBOL_login
    LI_SYMBOL(login)
#endif

#ifndef LI_SYMBOL_max_async_connections_per_thread
#define LI_SYMBOL_max_async_connections_per_thread
    LI_SYMBOL(max_async_connections_per_thread)
#endif

#ifndef LI_SYMBOL_max_sync_connections
#define LI_SYMBOL_max_sync_connections
    LI_SYMBOL(max_sync_connections)
#endif

#ifndef LI_SYMBOL_my_param
#define LI_SYMBOL_my_param
    LI_SYMBOL(my_param)
#endif

#ifndef LI_SYMBOL_my_param2
#define LI_SYMBOL_my_param2
    LI_SYMBOL(my_param2)
#endif

#ifndef LI_SYMBOL_my_symbol
#define LI_SYMBOL_my_symbol
    LI_SYMBOL(my_symbol)
#endif

#ifndef LI_SYMBOL_my_symbol2
#define LI_SYMBOL_my_symbol2
    LI_SYMBOL(my_symbol2)
#endif

#ifndef LI_SYMBOL_name
#define LI_SYMBOL_name
    LI_SYMBOL(name)
#endif

#ifndef LI_SYMBOL_non_blocking
#define LI_SYMBOL_non_blocking
    LI_SYMBOL(non_blocking)
#endif

#ifndef LI_SYMBOL_password
#define LI_SYMBOL_password
    LI_SYMBOL(password)
#endif

#ifndef LI_SYMBOL_port
#define LI_SYMBOL_port
    LI_SYMBOL(port)
#endif

#ifndef LI_SYMBOL_post_parameters
#define LI_SYMBOL_post_parameters
    LI_SYMBOL(post_parameters)
#endif

#ifndef LI_SYMBOL_primary_key
#define LI_SYMBOL_primary_key
    LI_SYMBOL(primary_key)
#endif

#ifndef LI_SYMBOL_read_only
#define LI_SYMBOL_read_only
    LI_SYMBOL(read_only)
#endif

#ifndef LI_SYMBOL_ssl_certificate
#define LI_SYMBOL_ssl_certificate
    LI_SYMBOL(ssl_certificate)
#endif

#ifndef LI_SYMBOL_ssl_ciphers
#define LI_SYMBOL_ssl_ciphers
    LI_SYMBOL(ssl_ciphers)
#endif

#ifndef LI_SYMBOL_ssl_key
#define LI_SYMBOL_ssl_key
    LI_SYMBOL(ssl_key)
#endif

#ifndef LI_SYMBOL_test1
#define LI_SYMBOL_test1
    LI_SYMBOL(test1)
#endif

#ifndef LI_SYMBOL_test2
#define LI_SYMBOL_test2
    LI_SYMBOL(test2)
#endif

#ifndef LI_SYMBOL_threads
#define LI_SYMBOL_threads
    LI_SYMBOL(threads)
#endif

#ifndef LI_SYMBOL_update_secret_key
#define LI_SYMBOL_update_secret_key
    LI_SYMBOL(update_secret_key)
#endif

#ifndef LI_SYMBOL_user
#define LI_SYMBOL_user
    LI_SYMBOL(user)
#endif

#ifndef LI_SYMBOL_validate
#define LI_SYMBOL_validate
    LI_SYMBOL(validate)
#endif

#ifndef LI_SYMBOL_x
#define LI_SYMBOL_x
    LI_SYMBOL(x)
#endif

#ifndef LI_SYMBOL_xxxx
#define LI_SYMBOL_xxxx
    LI_SYMBOL(xxxx)
#endif

